set timeoutlen=1000
set ttimeoutlen=0
set nocompatible
filetype off
set background=dark
colorscheme sunburst
syntax on
scriptencoding utf-8
set encoding=utf-8
set wrap
set ruler
set number
set cursorline
set mouse=a
set showcmd
set title
set gcr=n:blinkon0
set tabstop=4
set shiftwidth=4
set noexpandtab
set backspace=indent,eol,start
set foldmethod=indent
set foldcolumn=2
set foldlevel=99
set hlsearch
set incsearch
set ignorecase
set smartcase
set cc=80
set wildmenu
set wildmode=list:longest,full
set scrolloff=3
set history=10000
set autoread
set guifont=Ubuntu\ Mono\ derivative\ Powerline:h18
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif